### ISSUE TITLE
Thermostat problems with v3.0.0

### ISSUE THREAD

**Issue by robertklep** [swttt/com.swttt.homekit#108]
I wonder if this is a virtual thermostat that doesn't have a `measure_temperature` capability.

We don't actually check if the device _has_ that capability (we assume it does), also because the measured temperature (`CurrentTemperature`) is a required characteristic for the HomeKit service.

We could try three things:

* not add the `CurrentTemperature` characteristic if the device doesn't have `measure_temperature` (even though it's required; I don't know how HK will react to that)
* add the characteristic but call the callback with an error
* add the characteristic but call the callback with a fixed temperature (0, or something)

```
/lib/devices/thermostat.js:73
      callback(err, device.capabilitiesObj.measure_temperature.value);
                                                               ^

TypeError: Cannot read property 'value' of undefined
    at Characteristic.CurrentTemperature.<anonymous> (/lib/devices/thermostat.js:73:64)
```

```
---- stderr ----
(node:3030) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at onStateChange (/lib/devices/thermostat.js:147:63)
```

**Comment by nhassink** [comment]
Another option is to check if a device has all required capabilities before even exposing it to HomeKit

**Comment by robertklep** [comment]
Yeah, although I would probably be okay with exposing a device to HK if it has at least _one_ required capability, as long as HK can handle the "get" action returning an error.

**Comment by nhassink** [comment]
I’m not sure if the second error has the same cause... a switch without onoff seems strange
