### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Veldkornet** [swttt/com.swttt.homekit#150]
I noticed the following when HomeyKit starts. Looking at the error, I guess it's more of an Athom issue, but I've only seen it in HomeyKit so far:

HomeyKit v3.0.4
Homey v2.0.5

```
subscribing now happens automatically, there is no need to manually call subscribe anymore
{ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
    at d (/node_modules/athom-api/dist/index.js:1:1090029)
    at t.value (/node_modules/athom-api/dist/index.js:1:1092821)
    at t.value (/node_modules/athom-api/dist/index.js:1:1038876)
    at t.value (/node_modules/athom-api/dist/index.js:1:1092890)
    at t.value (/node_modules/athom-api/dist/index.js:1:1093121)
    at /node_modules/athom-api/dist/index.js:1:1045140
    at new Promise (<anonymous>)
    at new t (/node_modules/athom-api/dist/index.js:1:27620)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:1045110)
    at a (/node_modules/athom-api/dist/index.js:1:324246)
  name: 'MaxListenersExceededWarning',
  emitter:
   t {
     _security: { oauth2: [Object] },
     token:
      { name: 'homey_auth',
        isQuery: false,
        value: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
     _caches:
      { 'HomeyAPI.ManagerDevices.Device': [Object],
        'HomeyAPI.ManagerDevices.Capability': [Object] },
     _baseUrl: 'http://localhost:80',
     _basePath: '/api/manager/devices',
     _eventNS: '/realtime/manager/devices/',
     _eventURI: 'homey:manager:devices',
     authorizationUrl: '',
     managerName: 'ManagerDevices' },
  type: 'connect',
  count: 11 }
{ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit
    at d (/node_modules/athom-api/dist/index.js:1:1090029)
    at t.value (/node_modules/athom-api/dist/index.js:1:1092821)
    at t.value (/node_modules/athom-api/dist/index.js:1:1038876)
    at t.value (/node_modules/athom-api/dist/index.js:1:1092890)
    at t.value (/node_modules/athom-api/dist/index.js:1:1093121)
    at /node_modules/athom-api/dist/index.js:1:1045160
    at new Promise (<anonymous>)
    at new t (/node_modules/athom-api/dist/index.js:1:27620)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:1045110)
    at a (/node_modules/athom-api/dist/index.js:1:324246)
  name: 'MaxListenersExceededWarning',
  emitter:
   t {
     _security: { oauth2: [Object] },
     token:
      { name: 'homey_auth',
        isQuery: false,
        value: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
     _caches:
      { 'HomeyAPI.ManagerDevices.Device': [Object],
        'HomeyAPI.ManagerDevices.Capability': [Object] },
     _baseUrl: 'http://localhost:80',
     _basePath: '/api/manager/devices',
     _eventNS: '/realtime/manager/devices/',
     _eventURI: 'homey:manager:devices',
     authorizationUrl: '',
     managerName: 'ManagerDevices' },
  type: 'connect_error',
  count: 11 }
2019-03-26 12:43:39 [log] [HomekitApp] Started bridge
```

**Comment by robertklep** [comment]
The `MaxListenersExceededWarning` warning is a common Node.js warning that can safely be ignored.
