### ISSUE TITLE
Configurationcode for HomeKit is not accepted

### ISSUE THREAD

**Issue by Colijntje** [swttt/com.swttt.homekit#156]
After lost contact with HomeKit I reïnstalled the program but pairing with HomeKit failed. I got the messaged that configurationcode is wrong. Please advice what to do.

**Comment by robertklep** [comment]
So if I understand this correctly: the Home app on iOS can _find_ Homey on your local network, it just doesn't accept the security code (200-20-200)? If that's the case, are you sure that you are using [HomeyKit](https://apps.athom.com/app/com.swttt.homekit) and not one of the other HomeKit apps/implementations?

**Comment by Colijntje** [comment]
diYou understand correct. This is the message that I received  

Please check the diagnostic rapport
ee8adc76-a4fc-48af-a77e-6ad23802c423
--  
Nico Nagtzaam  

Van: Robert Klep <notifications@github.com>(mailto:notifications@github.com)
Beantwoorden: swttt/com.swttt.homekit <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 4 mei 2019 at 09:01:27
Aan: swttt/com.swttt.homekit <com.swttt.homekit@noreply.github.com>(mailto:com.swttt.homekit@noreply.github.com)
Cc: Colijntje <n.nagtzaam@tiscali.nl>(mailto:n.nagtzaam@tiscali.nl), Author <author@noreply.github.com>(mailto:author@noreply.github.com)
Onderwerp: Re: [swttt/com.swttt.homekit] Configurationcode for HomeKit is not accepted (#156)

**Comment by robertklep** [comment]
```
(node:29757) UnhandledPromiseRejectionWarning: session_expired: Er is een onbekende fout opgetreden [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1012832
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

That's an known issue with the current Homey firmware, I'm afraid. I think it's solved in the current experimental version, otherwise you can [look here](https://community.athom.com/t/app-group-2-3-1-stable/3168/162) for a temporary fix of the problem.
