### ISSUE TITLE
[1.0.12] App Crash 

### ISSUE THREAD

**Issue by Veldkornet** [swttt/com.swttt.homekit#29]
App started crashing after the update to 1.0.12

```
Hi!

Unfortunately, the app crashed while I was doing the following:

(...)

This is the stack trace:

/node_modules/has-node/src/characteristic.js:79
            throw new Error('Invalid Value: ' + value.toString());
            ^

Error: Invalid Value: true
    at Characteristic.setValue (/node_modules/has-node/src/characteristic.js:79:19)
    at t.device.on.state (/lib/devices/motionsensor.js:85:14)
    at c (/node_modules/athom-api/dist/index.js:1:748319)
    at t.a.emit (/node_modules/athom-api/dist/index.js:1:752136)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:740347)
    at o (/node_modules/athom-api/dist/index.js:1:748158)
    at t.a.emit (/node_modules/athom-api/dist/index.js:1:752098)
    at t.value (/node_modules/athom-api/dist/index.js:1:722746)
    at n.emit (/node_modules/athom-api/dist/index.js:1:215993)
    at n.onevent (/node_modules/athom-api/dist/index.js:1:209698)
```

**Comment by swttt** [comment]
Fixed, error when i added tamper and battery to the motion sensor :/
